[[redirects]]
  from = "/api/*"
  to = "https://api.dupr.gg/:splat"
  status = 200
  force = true
  headers = { Origin = "https://events.mydupr.com", Referer = "https://events.mydupr.com/" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
